### ISSUE TITLE
map() to new type

### ISSUE THREAD

**Issue by macster84** [jeromegamez/typed-collection#11]
Hi,

I do not know where else to raise that question.
I want to map() to a collection containing a new type but then get the exception:

 _collection only accepts objects of the following type(s):_

Being new to PHP in general, I am not sure if I am doing something wrong here entirely.
Looking at the source of the Laravel collection's map() method, I would assume that you cannot map() to a new collection type using your TypedCollection class.

```php
    public function map(callable $callback)
    {
        $keys = array_keys($this->items);

        $items = array_map($callback, $this->items, $keys);

        return new static(array_combine($keys, $items));
    }
```

The `new static()` would just create the same TypedCollection class that is fixed to a dedicated type, wouldn't it?

Any help would greatly be appreciated.
Many thanks
Cheers
Alex

**Comment by macster84** [comment]
Probably we could untype() it in the TypedCollection class, right?
```php
    /**
     * Run a map over each of the items.
     *
     * @param  callable  $callback
     * @return Collection
     */
    public function map(callable $callback)
    {
        return $this->untype()->map($callback);
    }
```

**Comment by jeromegamez** [comment]
Sorry for the late reply, I was in vacation mode, but I'm back now 🥳 

Your second suggestion was the one - I just released it as https://github.com/jeromegamez/typed-collection/releases/tag/5.1.0 - please let me know if you stumble upon problems.

Thank you for bringing this up! 🙌

**Comment by macster84** [comment]
> Sorry for the late reply, I was in vacation mode, but I'm back now 🥳

I feel you. Hope I didn't bring you back to abruptly ... ;-)

Thanks for the quick action!
Very much appreciated...
