### ISSUE TITLE
Shouldn't TypedCollection and LazyTypedCollection be abstract classes?

### ISSUE THREAD

**Issue by oibeal** [jeromegamez/typed-collection#13]
From what I see in the documentation the TypedCollection and LazyTypedCollection classes are not designed to be instantiated directly. An instance of these classes lacks values in the allowedTypes attribute so it is impossible to add values to the collections. It is also a protected attribute and there is no setter that allows adding the values later.

This fits the abstract class description, so I thought maybe doing it this way would make the classes even more stable by making it clear that you can't instantiate them.

**Comment by jeromegamez** [comment]
Agreed! I will update the classes and create a new release shortly. This is a breaking change because it's possible that used the collections without extending them (even if it doesn't make sense).

**Comment by jeromegamez** [comment]
https://github.com/jeromegamez/typed-collection/releases/tag/6.0.0

Thanks for addressing this!
