### ISSUE TITLE
Typed collection causes error in HasManyThrough relationship eager loading

### ISSUE THREAD

**Issue by JoshPJackson** [jeromegamez/typed-collection#14]
The `\Illuminate\Database\Eloquent\Relations\HasManyThrough::match` expects an instance of `\Illuminate\Database\Eloquent\Collection` to be given which is stopping eager loading working when querying.

So using the usual User -> Post -> Comment situation. 

I'll create a `CommentCollection` extending from the `TypedCollection` model, and set that with the `newCollection` method on the `Comment` model.

If I run the following:
```
$user = User::find(1);
$post = $user->posts()->first();
$comments = $post->comments;
```
Then everything works as it should. `$comments` will be an instance of `CommentCollection`.

However, eager loading with the following query causes an error:

User::with('posts.comments')->find(1);

This is the error:
` TypeError  Illuminate\Database\Eloquent\Relations\HasMany::match(): Argument #2 ($results) must be of type Illuminate\Database\Eloquent\Collection, App\Collections\CommentCollection given, called in vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php on line 758.`

Am I doing something wrong or is there something else I need to override other than the newCollection model?

**Comment by jeromegamez** [comment]
The collections of this package don't extend the Eloquent Collection class, so they apparently can't be used as custom collections for Eloquent models.

I didn't know this as well and had to look it, but the code example's type hint at https://laravel.com/docs/10.x/eloquent-collections#custom-collections seems to confirm it.

I don't understand the underlying magic that makes `User::with('posts.comments')` work, so I, unfortunately, can't tell you _why_ it doesn't work.

Thinking more about it, I don't think using the `TypedCollection` in that context is even necessary: entities retrieved with Eloquent are (I assume always) instances of the queried model.

Thinking even more (😅) about it, this package might be ready to be archived - with Laravel 10's support for native type annotations and tools like PHPStan/Larastan, typed collections can be enforced by using static type analysis 🤔.

I hope this helps, despite me not being able to provide a solution within this package for this concrete use case. 🙇🏼‍♂️

**Comment by JoshPJackson** [comment]
Fair enough, thanks for your reply
