### ISSUE TITLE
Issue with toArray methods since Laravel 6.0

### ISSUE THREAD

**Issue by francoislevesque** [jeromegamez/typed-collection#2]
I have the following code:

```
$col = new TestCollection();

$col->push(new TestItem([1,2,3]));
 $col->push(new TestItem([1,2,3]));

$col->toArray();
```

```
class TestItem implements Arrayable
{
    private $items;
    
    public function __construct($items)
    {
        $this->items;
    }

    public function toArray()
    {
        return $this->items;
    }
}
```
```
class TestCollection extends TypedCollection
{
    protected static $allowedTypes = [TestItem::class];
}
```
It throws the following exception:
`InvalidArgumentException: A Tests\Unit\Model\TestCollection collection only accepts objects of the following type(s): Tests\Unit\Model\TestItem.`

Do you know what can cause this error?
Thanks!

**Comment by jeromegamez** [comment]
I believe this has something to do with namespaces 🤔 - it looks as if your `TestItem` class is not declared in the `Tests\Unit\Model` namespace... is it perhaps declared without a namespace declaration?

**Comment by jeromegamez** [comment]
I noticed the title of the issue ("Issue with toArray methods since Laravel 6.0") just now, after my response 😅 - did your code work as-is with Laravel 5.8?

**Comment by francoislevesque** [comment]
Just did a simple test with Laravel 5.8 & gamez/typed-collection 2.1:

```
<?php

namespace Tests\Unit;

use Gamez\Illuminate\Support\TypedCollection;
use Tests\TestCase;
use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        $col = new TestCollection();

        $col->push(new TestItem([1,2,3]));
        $col->push(new TestItem([1,2,3]));

        $col->toArray();
    }
}

class TestItem implements Arrayable
{
    private $items;
    
    public function __construct($items)
    {
        $this->items;
    }

    public function toArray()
    {
        return $this->items;
    }
}

class TestCollection extends TypedCollection
{
    protected static $allowedTypes = [TestItem::class];
}
```
And I get no exception! 
The error appears back when I update to 6.*.

Thanks for your quick reply :)

**Comment by jeromegamez** [comment]
I just added a fix in the referenced PR - could you give it a go and see if it works for you as well and that I didn‘t miss anything? 

(This reply took longer, we were just lucky with the first one - it was ~2:30am and I went 😴 right after 😅)

**Comment by francoislevesque** [comment]
haha no problem, I just woke up 😄 Still pretty fast ^^
The problem is solved on my end, the fix is perfect!

**Comment by jeromegamez** [comment]
Here's the new release: [2.2.0](https://github.com/jeromegamez/typed-collection/releases/tag/2.2.0) 🥳, it should show up in a `composer update` soon 🤞

Thanks for bringing this up!
