### ISSUE TITLE
Does not work without the illuminate/support package

### ISSUE THREAD

**Issue by ordermind** [jeromegamez/typed-collection#6]
In composer.json you require the library tightenco/collect, presumably to avoid requiring the whole illuminate/support package. However, from what I can see you never use those classes. Instead you extend from illuminate/support, e.g. Illuminate\Support\Collection. If my assumption is correct and you do mean to use tightenco/collect, you need to extend those classes instead. Then you should be able to get rid of illuminate/support in dev as well.

**Comment by jeromegamez** [comment]
`tightenco/collect`'s classes are aliased to `illuminate/support`'s classes (see https://github.com/tightenco/collect/blob/laravel-6-ongoing/src/Collect/Support/alias.php), so this shouldn't be an issue :think:

At least it hasn't until Laravel 7.x - while testing your assumption I noticed that the collection signatures have changed and produce some warnings now 😖😅

Thank you for your input 🌺! I'll address the 7.x changes probably in a new release 🤞

**Comment by jeromegamez** [comment]
I just created a new release that should address all issues (assuming that I understood everything correctly and did not make mistakes 😅). Please let me know if you think there's more to do.

Thanks again for bringing this up!
