### ISSUE TITLE
Collection::push is broken since version 3

### ISSUE THREAD

**Issue by pjordaan** [jeromegamez/typed-collection#7]
I tried to upgrade my application to Laravel 7. My unittests failed on the typed collection. My code uses TypedCollection::push.

The problem is that since Laravel 7, push is now a variadic function, but TypedCollection::push calls the parent::push incorrectly:

```php
public function push(...$values)
{
    foreach ($values as $value) {
        $this->assertValidType($value);
    }

    return parent::push($values);
}
```
Using TypedCollection::push adds the item in an array of one element instead  which is incorrect.

It should have been:
```php
public function push(...$values)
{
    foreach ($values as $value) {
        $this->assertValidType($value);
    }

    return parent::push(...$values);
}
```

**Comment by jeromegamez** [comment]
Uh, this ~is~was bad, thanks for letting me know! 🌺 I just released 3.0.1 and I hope that this is now fixed 🤞 

(Good to know that someone is actually using this 🙈)

**Comment by pjordaan** [comment]
Hi, thanks for fixing it. I'm surprised the unit tests did not find this one. If I look at the tests all they do is test if the method does not crash, but none of the test check if the contents was properly added in the collection...

**Comment by jeromegamez** [comment]
Human shortcoming 😅, I forgot that variadic arguments and arrays would need more checks - I didn't think of it because pre-variadic, the typed collections only added checks and otherwise just proxy calls without modifying the actual items.

In the end, I'm glad that you found the error and it was possible to fix it. Sorry for the inconvenience though!

**Comment by jeromegamez** [comment]
I'm closing the issue now, but feel free to continue the conversation :)
